---
sidebar: sidebar 
permalink: create-sandbox-clone.html 
keywords: create, clone, sandbox 
summary: 'Créez un clone sandbox dans l"usine de workloads BlueXP  pour les bases de données.' 
---
= Créez un clone sandbox dans l'usine de workloads BlueXP  pour les bases de données
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La création d'un clone sandbox d'une base de données dans l'usine de workloads BlueXP  pour les bases de données vous permet d'utiliser le clone à des fins de développement, de test, d'intégration, d'analytique, de formation, d'assurance qualité, etc., sans modifier la base de données source.

.Description de la tâche
Un clone sandbox est créé à partir de l'instantané le plus récent de la base de données source. Il peut être cloné dans le même serveur Microsoft SQL que la base de données source ou cloné dans un autre serveur Microsoft SQL Server tant qu'ils partagent le même système de fichiers FSX pour ONTAP.

.Avant de commencer
Assurez-vous de remplir les conditions préalables suivantes avant de créer un clone sandbox.

Informations d'identification et autorisations:: Vous devez link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Informations d'identification du compte AWS et autorisations _read_ ou _automate_ mode"^]créer un clone sandbox en usine de la charge de travail.
+
--
Vous pouvez également utiliser la Codebox pour copier un modèle partiellement terminé ou créer un modèle terminé afin de créer le clone sandbox en dehors de l'usine de la charge de travail à l'aide de l'API REST. link:https://docs.netapp.com/us-en/workload-setup-admin/codebox-automation.html["En savoir plus sur l'automatisation de Codebox"^].

--
Microsoft SQL Server:: Vous devez disposer d'un serveur Microsoft SQL Server géré en usine pour que les bases de données puissent héberger le nouveau clone sandbox.
AWS Systems Manager:: Vérifiez que le `NT Authority\SYSTEM` privilège utilisateur est activé sur l'hôte Microsoft SQL via AWS Systems Manager.
Base de données source:: Une base de données source est nécessaire pour le clone.


.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans la mosaïque bases de données, sélectionnez *aller à l'inventaire des bases de données*.
. Dans bases de données, sélectionnez l'onglet *sandbox*.
. Dans l'onglet sandbox, sélectionnez *Créer un nouveau bac à sable*.
. Sur la page Créer un nouveau sandbox, sous Source de base de données, fournissez les éléments suivants :
+
.. *Hôte de la base de données source* : sélectionnez l'hôte de la base de données source.
.. *Instance de base de données source* : sélectionnez l'instance de base de données source.
.. *Base de données source* : sélectionnez la base de données source à partir de laquelle cloner.


. Sous cible de la base de données, indiquez les informations suivantes :
+
.. *Hôte de base de données cible* : sélectionnez un hôte de base de données cible pour le clone sandbox qui se trouve dans le même VPC et qui possède le même système de fichiers FSX pour ONTAP que l'hôte source.
.. *Instance de base de données cible* : sélectionnez l'instance de base de données cible pour le clone sandbox.
.. *Base de données cible* : saisissez un nom pour le clone sandbox.


. *Mount* : lors du clonage d'une base de données SQL contenant plusieurs fichiers de données et/ou de journaux, la fabrique de workloads clone tous les fichiers sous la lettre de lecteur attribuée ou définie automatiquement.
+
Sélectionnez l'une des options suivantes :

+
.. *Affectation automatique du point de montage*
.. *Définir le chemin du point de montage*
+
Pour définir le chemin du point de montage, procédez comme suit :

+
*** Entrez la lettre du lecteur correspondant au chemin du fichier de données.
*** Entrez la lettre du lecteur correspondant au chemin du fichier journal.




. *Définir la balise* : sélectionnez une balise pour définir le clone sandbox.
. Cliquez sur *Créer*.


Pour vérifier la progression du travail, accédez à l'onglet *surveillance du travail*.
