---
sidebar: sidebar 
permalink: create-database.html 
keywords: create, database, creation, Microsoft SQL 
summary: Créez une base de données Microsoft SQL avec NetApp Workload Factory for Databases. 
---
= Créer une base de données Microsoft SQL dans NetApp Workload Factory pour les bases de données
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La création d’une nouvelle base de données Microsoft SQL vous permet de gérer la ressource dans NetApp Workload Factory for Databases.

.Description de la tâche
Lors de la création de la base de données, deux nouveaux volumes sont créés dans le système de fichiers FSX pour ONTAP, composé de LUN indépendants qui hébergent les données et les fichiers journaux de la base de données. Les fichiers de base de données de la nouvelle base de données sont à provisionnement fin et ne consomment que quelques Mo de la taille totale allouée à la nouvelle base de données.

Si vous souhaitez isoler le stockage de la base de données, vous pouvez le faire en utilisant un _point de montage virtuel_. Le point de montage virtuel vous permet de consolider des bases de données sur quelques lecteurs communs de l'hôte.

La création d'une base de données dans Workload Factory nécessite les autorisations de _visualisation, de planification et d'analyse_. Vous pouvez également copier ou télécharger un modèle de code partiellement rempli pour terminer l'opération en dehors de Workload Factory. link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html["Découvrez les autorisations de Workload Factory"^] pour choisir le mode que vous souhaitez utiliser.


NOTE: Les serveurs Microsoft SQL utilisant le protocole SMB ne prennent pas en charge la création de bases de données.

.Avant de commencer
Assurez-vous de remplir les conditions préalables suivantes avant de créer une nouvelle base de données.

* *Identifiants et autorisations* : Vous devez posséder link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Identifiants du compte AWS et autorisations de _visualisation, de planification et d'analyse_"^] pour créer une nouvelle base de données dans Workload Factory.
+
Vous pouvez également utiliser la Codebox pour copier un modèle afin de déployer une base de données hors de l'usine de la charge de travail à l'aide de l'API REST. link:https://docs.netapp.com/us-en/workload-setup-admin/codebox-automation.html["En savoir plus sur l'automatisation de Codebox"^].

* *Hôte Windows* : vous devez disposer de suffisamment de lettres de lecteur disponibles sur le serveur Microsoft SQL Server pour créer de nouveaux lecteurs pour la nouvelle base de données si vous utilisez le mode _Création rapide_.
* *Microsoft SQL Server* : vous devez disposer d’un serveur Microsoft SQL Server géré dans la fabrique de charges de travail pour que les bases de données hébergent la nouvelle base de données.
* *AWS Systems Manager* : Assurez-vous que `NT Authority\SYSTEM` le privilège utilisateur est activé dans l'hôte Microsoft SQL via AWS Systems Manager.




== Créer une base de données

Vous pouvez utiliser les modes de déploiement _Création rapide_ ou _Création avancée_ pour effectuer cette tâche dans Workload Factory.

[role="tabbed-block"]
====
.Création rapide
--
.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans la mosaïque bases de données, sélectionnez *aller à l'inventaire des bases de données*.
. Dans le menu Bases de données, sélectionnez *Inventaire*.
. Dans l’inventaire, sélectionnez *Microsoft SQL Server* comme type de moteur de base de données.
. Sélectionnez un serveur de base de données avec une instance de serveur SQL gérée pour créer la base de données.
. Cliquez sur le menu d’action de l’instance gérée, puis sélectionnez *Créer une base de données utilisateur*.
. Sur la page Créer une base de données utilisateur, sous informations sur la base de données, fournissez les informations suivantes :
+
.. *Nom de la base de données* : entrez le nom de la base de données.
.. *Classement* : sélectionnez un classement pour la base de données. Le classement par défaut SQL_Latin1_General_CP1_ci_AS » sur Microsoft SQL Server est sélectionné.


. Sous Paramètres de fichier, fournissez les informations suivantes :
+
.. *Mode Paramètres de fichier* : sélectionnez *création rapide*.
.. *Noms de fichiers et chemin* :
+
*** *Nom du fichier de données* : entrez le nom du fichier de données.
*** *Nom du fichier journal* : entrez le nom du fichier journal.


.. *Taille des fichiers* : entrez la taille des données et du journal de la base de données.


. Cliquez sur *Créer*.
+
Sinon, si vous voulez modifier l'un de ces paramètres par défaut maintenant, changez le *mode Paramètres du fichier* en *mode de création avancée*.



--
.Création avancée
--
.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans la mosaïque bases de données, sélectionnez *aller à l'inventaire des bases de données*.
. Dans le menu Bases de données, sélectionnez *Inventaire*.
. Dans l’inventaire, sélectionnez *Microsoft SQL Server* comme type de moteur de base de données.
. Sélectionnez un serveur de base de données avec une instance de serveur SQL gérée pour créer la base de données.
. Cliquez sur le menu d’action de l’instance gérée, puis sélectionnez *Créer une base de données utilisateur*.
. Sélectionnez *Créer une base de données utilisateur*.
. Sur la page Créer une base de données utilisateur, sous informations sur la base de données, fournissez les informations suivantes :
+
.. *Nom de la base de données* : entrez le nom de la base de données.
.. *Classement* : sélectionnez le classement de la base de données. Le classement par défaut SQL_Latin1_General_CP1_ci_AS » sur Microsoft SQL Server est sélectionné.


. Sous Paramètres de fichier, fournissez les informations suivantes :
+
.. *Mode Paramètres de fichier* : sélectionnez *création avancée*.
.. *Noms de fichiers et chemin* :
+
... *Fichier de données* : sélectionnez une lettre de lecteur et entrez le nom du fichier de données.
+
Si vous le souhaitez, cliquez sur la case *point de montage virtuel*.

... *Fichier journal* : sélectionnez une lettre de lecteur et entrez le nom du fichier journal.
+
Si vous le souhaitez, cliquez sur la case *point de montage virtuel*.



.. *Taille des fichiers* : entrez la taille des données et du journal de la base de données.


. Cliquez sur *Créer*.


--
====
Si vous avez créé l'hôte de base de données, vous pouvez vérifier la progression du travail dans l'onglet *surveillance du travail*.
