---
sidebar: sidebar 
permalink: known-limitations.html 
keywords: limitations, databases 
summary: Les limitations connues identifient les plateformes, les périphériques ou les fonctions qui ne sont pas pris en charge par cette version du produit, ou qui ne fonctionnent pas correctement avec elle. Examinez attentivement ces limites. 
---
= Limitations connues de l'usine de workloads BlueXP  pour les bases de données
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Les limitations connues identifient les plateformes, les périphériques ou les fonctions qui ne sont pas pris en charge par cette version du produit, ou qui ne fonctionnent pas correctement avec elle. Examinez attentivement ces limites.



== Prise en charge de la détection d'instance

Workload Factory prend en charge la détection des instances PostgreSQL exécutées uniquement sur les systèmes d'exploitation Amazon Linux et des instances Oracle exécutées uniquement sur Red Hat Enterprise Linux.



== Prise en charge de la version d'image ami

Nous n'affichons que quatre versions ou révisions récentes d'images ami pour chaque version SQL. Nous n'autorisons pas l'installation à partir d'une image ami antérieure aux quatre dernières versions.



== Ami personnalisé

Le déploiement avec un ami personnalisé suppose que le support d'installation est présent dans l'image. Ceci est nécessaire pour la configuration FCI pour les raisons suivantes :

* Pour désinstaller et reconfigurer pour former le cluster FCI
* Lors de la sélection d'un classement autre que celui défini dans l'image pour un déploiement autonome


Dans le cadre du déploiement, l'usine de workloads n'installe pas d'ami personnalisé avec plusieurs instances de Microsoft SQL Server. Seule l'instance par défaut de Microsoft SQL Server est sélectionnée et configurée dans le cadre du déploiement.



== Effectuez une restauration et réessayez en cas d'échec des déploiements

La restauration et les tentatives de reprise pour les déploiements en échec ne sont pas prises en charge dans l'usine de la charge de travail. Vous pouvez revenir en arrière ou réessayer une pile défaillante à partir de la console CloudFormation dans AWS.



== Restauration des ressources Active Directory et DNS

Les ressources DNS suivantes ne sont pas supprimées d'Active Directory et DNS lorsque vous effectuez une restauration d'un test ou que vous avez échoué au déploiement depuis la console CloudFormation dans AWS :

* Chaque nœud du déploiement SQL à son adresse IP de gestion
* Nom du cluster Windows vers les adresses IP secondaires réservées des instances EC2 en cas de FCI
* Nom de FCI SQL vers les deux adresses IP réservées des deux instances EC2 de FCI


Vous devrez les nettoyer manuellement ou attendre que le domaine purge les entrées obsolètes.



== Prise en charge de la configuration des groupes de disponibilité permanente

En usine de charges de travail, la gestion des configurations de groupes de disponibilité always-on n'est pas prise en charge.



== Clés de chiffrement personnalisées

Les clés de chiffrement personnalisées pour FSX pour ONTAP ne sont pas répertoriées en fonction de l'applicabilité du service. Vous devez choisir la clé appropriée. Les clés gérées AWS sont filtrées en fonction de leur applicabilité au service.



== Modèle CloudFormation

Un modèle CloudFormation téléchargé ou copié généré par Codebox (fichier YAML) a une période de conservation limitée de sept jours.



== Prise en charge de sandbox

Le nombre maximum de clones sandbox pouvant être créés à partir d'un serveur de base de données est de 90.



== Détection et gestion de Microsoft SQL Server

La détection de Microsoft SQL Server n'est pas enregistrée. Chaque fois que vous accédez aux bases de données en usine, la détection de Microsoft SQL Server s'exécute à nouveau pour identifier les installations SQL dans la région.



== Découvrez les économies

Dans l'onglet Inventaire, le coût estimé affiché pour chaque instance de Microsoft SQL est calculé au niveau du système de fichiers FSX pour ONTAP et non pour les volumes hébergeant l'instance SQL.



== Plusieurs solutions FSX pour les systèmes de fichiers ONTAP

Workload Factory ne prend pas en charge la création ou l'enregistrement de configurations pour Microsoft SQL Server avec plusieurs systèmes de fichiers FSX pour ONTAP. Un seul déploiement de configuration de système de fichiers FSX pour ONTAP est pris en charge.



== Limitations de l'optimisation



=== Optimisation du dimensionnement approprié des ressources de calcul

Lors du passage à certains types d'instances, la configuration réseau peut être réinitialisée, ce qui peut entraîner un échec de la connexion au nœud pendant l'optimisation et entraîner l'échec du travail. Une intervention manuelle peut être nécessaire pour vérifier et mettre à jour le paramètre DNS et les sessions iSCSI. Pour plus d'informations sur les limites de redimensionnement EC2, reportez-vous à la sectionlink:https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/resize-limitations.html["Documentation d'Amazon Elastic Compute Cloud"^].



=== Optimisation de la configuration ONTAP et OS

L'optimisation en bloc de plusieurs instances SQL Server n'est pas prise en charge pour la configuration ONTAP et la configuration du système d'exploitation.



=== Évaluation des correctifs du système d'exploitation pour l'optimisation

L'évaluation des correctifs du système d'exploitation effectuée à des fins d'optimisation peut ne pas fonctionner sur un réseau privé. L'évaluation repose sur AWS Patch Manager. Pour savoir comment appliquer des correctifs aux instances Windows EC2 dans un réseau privé, reportez-vous à la section link:https://aws.amazon.com/blogs/mt/how-to-patch-windows-ec2-instances-in-private-subnets-using-aws-systems-manager/["Blog AWS Cloud Operations « Comment corriger les instances Windows EC2 dans des sous-réseaux privés à l'aide d'AWS Systems Manager »"^].



== Calcul des économies sur site

Les calculs des économies et des pourcentages de la taille du volume pour le stockage sur site Microsoft SQL Server ne sont pas pris en compte.



== Évaluation de la réplication entre les régions

* L'évaluation d'optimisation ne peut pas déterminer si la réplication interrégionale (CRR) est utilisée lorsque le système de fichiers FSX pour ONTAP cible se trouve dans un autre compte AWS.
* L'usine de charge de travail évalue uniquement la configuration CRR du système de fichiers source FSX pour ONTAP.

