---
sidebar: sidebar 
permalink: learn-databases.html 
keywords: Databases 
summary: 'NetApp Workload Factory for Databases est un service de déploiement et de maintenance de bases de données de bout en bout avec des meilleures pratiques intégrées pour l"optimisation, le clonage fin automatique et les capacités de surveillance et de résolution.' 
---
= En savoir plus sur NetApp Workload Factory pour les bases de données
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory for Databases est un service de déploiement et de maintenance de bases de données de bout en bout avec des meilleures pratiques intégrées pour l'optimisation, le clonage fin automatique et les capacités de surveillance et de résolution.



== Qu'est-ce que NetApp Workload Factory pour les bases de données ?

NetApp Workload Factory for Databases détecte, évalue, planifie, provisionne et déplace les données Microsoft SQL Server vers les déploiements Amazon FSx for NetApp ONTAP (FSx for ONTAP) optimisés pour répondre à vos attentes en matière de performances et de coûts tout en adhérant aux meilleures pratiques du secteur.  Tout au long du cycle de vie, NetApp Workload Factory for Databases offre une optimisation et une gestion continues des bases de données sur FSx for ONTAP.

Pour plus d'informations sur Workload Factory, reportez-vous aulink:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html["Présentation de Workload Factory"^] .



== Avantages de Workload Factory pour les bases de données autogérées

Workload Factory propose les meilleures pratiques bénéfiques et l'automatisation suivantes pour les bases de données autogérées.



=== Et des meilleures pratiques

* Connaissance intégrée du cloud AWS, des serveurs Microsoft Windows et SQL et de NetApp ONTAP pour les déploiements de serveurs SQL sur les instances EC2.
* Un déploiement optimisé pour un coût total de possession optimal.
* Automatisation des déploiements de bout en bout, conformément aux bonnes pratiques AWS, Microsoft et ONTAP.
* Le mode de déploiement _Création rapide_ vous aide à éviter les pièges potentiels liés à la configuration manuelle.




=== Automatisation avec Workload Factory Codebox

Workload Factory introduit l'automatisation intégrée avec _Codebox_.  Le Codebox offre les avantages d'automatisation suivants :

* *Génération de code snippet* : des snippets IAC (Infrastructure-as-Code) sont générés lors de la création de ressources, permettant une intégration transparente avec les workflows d'orchestration existants.
* *Copilote d'infrastructure en tant que code* : Codebox est un copilote d'infrastructure en tant que code (IaC) qui aide les développeurs et DevOps à générer du code pour exécuter n'importe quelle opération prise en charge par Workload Factory.
* *Afficheur de code et catalogue d'automatisation*: La Codebox fournit un afficheur de code pour une analyse rapide de l'automatisation et un catalogue d'automatisation pour une réutilisation rapide future.




=== Fonctionnalités de Workload Factory pour les bases de données

Workload Factory for Databases offre les fonctionnalités suivantes :

* *Déploiements simples et rapides* : simplifiez et rationalisez votre expérience de provisionnement en sélectionnant les réponses aux questions de spécifications et en éliminant le temps généralement requis pour étudier la façon de provisionner et de configurer votre serveur Microsoft SQL Server sur AWS.
* *Orchestration automatisée* : disponible via la console Workload Factory avec les modes de déploiement de création _Rapide_ et _Avancé_, le Chatbot et AWS CloudFormation via Codebox.
* *Fonctionnalités intégrées* : utilisez les meilleures pratiques NetApp, Microsoft et Amazon et les sélections de ressources AWS intégrées à la configuration du déploiement.
* *Estimation des coûts* : évaluez les économies potentielles à l'aide du calculateur d'économies qui estime et détaille les coûts détaillés du stockage, du calcul, des licences SQL, des snapshots et des clones pour les déploiements Microsoft SQL Server existants avec Elastic Block Store et FSX pour serveur de fichiers Windows par rapport à FSX pour ONTAP.
* *Modèles d'automatisation réutilisables* : créez, réutilisez et personnalisez les modèles CloudFormation à partir de Workload Factory Codebox pour les futurs déploiements Microsoft SQL Server dans plusieurs environnements.
* *Découverte et provisionnement des ressources AWS* : détectez automatiquement les serveurs Microsoft SQL sur FSX pour ONTAP, FSX pour serveurs de fichiers Windows et Elastic Block Store déployés à partir de votre compte AWS. L'inventaire des bases de données sert de point de départ à l'exploration des possibilités d'économies pour les serveurs d'autres systèmes de stockage AWS ou d'un outil de gestion pour les serveurs et instances FSX pour ONTAP.
* *Création de sandbox* : créez un environnement de base de données isolé à la demande qui peut être utilisé pour les tests, l'intégration, les diagnostics et la formation, sans affecter les données de production.
* *Création de base de données* : créez une base de données utilisateur pour vos serveurs Microsoft SQL existants avec les modes _Quick_ ou _Advanced_ create pour configurer votre classement de base de données, les noms de fichiers et les tailles. La configuration du stockage est incluse.
* *Surveillance des travaux* : surveillez et suivez la progression de l'exécution des travaux de la base de données et diagnostiquez et résolvez les problèmes en cas d'échec.
* *Optimisation continue* : analyse en continu votre environnement Microsoft SQL Server hors ligne, vous fournissant un rapport complet des informations, opportunités et recommandations pour vous aider à atteindre l'excellence opérationnelle.




== Avantages d'Amazon FSX pour ONTAP pour les bases de données autogérées

* *Durabilité, disponibilité et fiabilité* : FSX for ONTAP offre de nombreuses fonctionnalités qui améliorent la durabilité et la disponibilité des bases de données autogérées hébergées sur FSX for ONTAP, telles que la haute disponibilité prenant en charge les déploiements dans des zones de disponibilité unique et multiple, les snapshots intégrant la cohérence applicative, la reprise après incident améliorée grâce à la réplication et une sauvegarde efficace.
* *Performances et évolutivité* : FSX pour ONTAP offre l'optimisation des performances avec un débit élevé, une faible latence, des connexions réseau haut débit et l'évolutivité avec plusieurs systèmes de fichiers pour faire évoluer les performances d'agrégats requises pour une charge de travail.
* *Gestion et efficacité des données* : FSX pour ONTAP offre de nombreuses fonctionnalités qui améliorent la gestion et l'efficacité des données, telles que les clones fins compacts, le provisionnement fin, la compression et la déduplication, et le Tiering des données rarement utilisées dans le pool de capacité.


link:https://docs.netapp.com/us-en/workload-fsx-ontap/learn-fsx-ontap.html["En savoir plus sur FSx pour ONTAP pour Workload Factory"^] .



=== Modes de fonctionnement dans Workload Factory

Trois modes de fonctionnement différents - _de base_, _lecture seule_ et _lecture/écriture_ - offrent des options flexibles pour le déploiement à l'intérieur et à l'extérieur de Workload Factory. Bénéficiez d'une valeur immédiate en mode zéro confiance en mode _basic_ avec des extraits de code à utiliser en dehors de Workload Factory. Obtenez une valeur incrémentielle avec une confiance incrémentielle dans les modes _lecture seule_ et _lecture/écriture_.

En savoir plus sur link:https://docs.netapp.com/us-en/workload-setup-admin/operational-modes.html["modes de fonctionnement dans Workload Factory"^] .



== Outils pour utiliser NetApp Workload Factory

Vous pouvez utiliser NetApp Workload Factory avec les outils suivants :

* *Console Workload Factory* : La console Workload Factory fournit une vue visuelle et holistique de vos applications et projets.
* * Console NetApp * : la console NetApp fournit une expérience d'interface hybride afin que vous puissiez utiliser Workload Factory avec d'autres services de données NetApp .
* *Demandez-moi* : utilisez l'assistant IA Ask me pour poser des questions et en savoir plus sur Workload Factory sans quitter la console Workload Factory. Accédez à Demandez-moi depuis le menu d'aide de Workload Factory.
* *CloudShell CLI* : Workload Factory inclut une CLI CloudShell pour gérer et exploiter les environnements AWS et NetApp sur plusieurs comptes à partir d'une seule CLI basée sur un navigateur. Accédez à CloudShell depuis la barre supérieure de la console Workload Factory.
* *API REST* : utilisez les API REST de Workload Factory pour déployer et gérer vos systèmes de fichiers FSx for ONTAP et d'autres ressources AWS.
* *CloudFormation* : utilisez le code AWS CloudFormation pour effectuer les actions que vous avez définies dans la console Workload Factory afin de modéliser, provisionner et gérer les ressources AWS et tierces de la pile CloudFormation dans votre compte AWS.
* *Fournisseur Terraform NetApp Workload Factory* : utilisez Terraform pour créer et gérer les workflows d'infrastructure générés dans la console Workload Factory.




== Configurations compatibles

Workload Factory prend en charge les moteurs de base de données, versions, systèmes d'exploitation et modèles de déploiement suivants conformément aux meilleures pratiques AWS, NetApp ONTAP, Microsoft SQL Server, Oracle et PostgreSQL.

[cols="1,1,1,1"]
|===
| Moteur | Version | Système opérateur | Modèle de déploiement 


| Microsoft SQL Server | SQL Server 2016 | Windows Server 2016 | FCI, instance unique 


| Microsoft SQL Server | SQL Server 2019 | Windows Server 2016 | FCI, instance unique 


| Microsoft SQL Server | SQL Server 2022 | Windows Server 2016 | FCI, instance unique 


| Microsoft SQL Server | SQL Server 2016 | Windows Server 2019 | FCI, instance unique 


| Microsoft SQL Server | SQL Server 2019 | Windows Server 2019 | FCI, instance unique 


| Microsoft SQL Server | SQL Server 2022 | Windows Server 2019 | FCI, instance unique 


| Microsoft SQL Server | SQL Server 2016 | Windows Server 2022 | FCI, instance unique 


| Microsoft SQL Server | SQL Server 2019 | Windows Server 2022 | FCI, instance unique 


| Microsoft SQL Server | SQL Server 2022 | Windows Server 2022 | FCI, instance unique 


| Microsoft SQL Server | SQL Server 2017 | N'importe lequel | FCI, instance unique 


| Microsoft SQL Server | SQL Server 2016, 2017, 2019, 2022 | N'importe lequel | FCI, instance unique 


| Microsoft SQL Server | SQL Server 2016, 2019, 2022 | N'importe lequel | Groupes de disponibilité toujours actifs 


| Oracle | 19c | RHEL, SuSe Linux | Autonome (locataire unique/multi-locataire) 


| Oracle | 21c | RHEL, SuSe Linux | Autonome (locataire unique/multi-locataire) 


| Oracle | 19c | RHEL, SuSe Linux | Autonome (locataire unique/multi-locataire) 


| Oracle | 21c | RHEL, SuSe Linux | Autonome (locataire unique/multi-locataire) 


| Oracle | 19c | RHEL, SuSe Linux | Autonome avec ASM (locataire unique/multi-locataire) 


| Oracle | 21c | RHEL, SuSe Linux | Autonome avec ASM (locataire unique/multi-locataire) 


| Oracle | 19c | RHEL, SuSe Linux | Dataguard 


| Oracle | 21c | RHEL, SuSe Linux | Dataguard 


| PostgreSQL | PostgreSQL 15 | AMI Amazon Linux 2023 | HA, instance autonome 


| PostgreSQL | PostgreSQL 16 | AMI Amazon Linux 2023 | HA, instance autonome 
|===


== Services AWS intégrés

Les bases de données incluent les services AWS intégrés suivants :

* CloudFormation
* Simple notification Service
* CloudWatch
* System Manager
* Responsable secrets




== Régions

Les bases de données sont prises en charge dans toutes les régions commerciales où FSX pour ONTAP est pris en charge. https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["Affichez les régions Amazon prises en charge."^]

Les régions AWS suivantes ne sont pas prises en charge :

* Régions de Chine
* GovCloud (USA)
* Le cloud secret
* Meilleur cloud secret




== Obtenir de l'aide

Amazon FSX pour NetApp ONTAP est une solution propriétaire AWS. Pour toute question ou tout problème de support technique associé à votre système de fichiers FSX for ONTAP, à votre infrastructure ou à toute solution utilisant ce service, utilisez le centre de support de votre console de gestion AWS pour ouvrir un dossier de support avec AWS. Sélectionnez le service “FSX pour ONTAP” et la catégorie appropriée. Fournissez les informations restantes nécessaires pour créer un dossier de demande de support AWS.

Pour des questions générales sur Workload Factory ou les applications et services Workload Factory, reportez-vous àlink:get-help.html["Obtenez de l'aide pour NetApp Workload Factory pour les bases de données"] .
