---
sidebar: sidebar 
permalink: learn-databases.html 
keywords: Databases 
summary: 'NetApp Workload Factory for Databases est un service de déploiement et de maintenance de bases de données de bout en bout avec des meilleures pratiques intégrées pour l"optimisation, le clonage fin automatique et les capacités de surveillance et de résolution.' 
---
= En savoir plus sur NetApp Workload Factory pour les bases de données
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory for Databases est un service de déploiement et de maintenance de bases de données de bout en bout avec des meilleures pratiques intégrées pour l'optimisation, le clonage fin automatique et les capacités de surveillance et de résolution.



[[what-is-netapp-workload-factory-for-databases]]
== Qu'est-ce que NetApp Workload Factory pour les bases de données ?

NetApp Workload Factory for Databases découvre, évalue, planifie, provisionne et migre les données Microsoft SQL Server, PostgreSQL et Oracle vers Amazon FSx for NetApp ONTAP (FSx for ONTAP) des déploiements optimisés pour répondre à vos attentes en matière de performance et d’économies, tout en respectant les meilleures pratiques du secteur. NetApp Workload Factory for Databases optimise et gère en continu les bases de données sur FSx for ONTAP.

Pour plus d'informations sur Workload Factory, reportez-vous aulink:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html["Présentation de Workload Factory"^] .



[[workload-factory-benefits-for-self-managed-databases]]
== Avantages de Workload Factory pour les bases de données autogérées

Workload Factory fournit des bonnes pratiques et de l'automatisation pour les bases de données autogérées.



[[best-practices]]
=== Et des meilleures pratiques

* Connaissance intégrée du cloud AWS, des serveurs Microsoft Windows et SQL et de NetApp ONTAP pour les déploiements de serveurs SQL sur les instances EC2.
* Un déploiement optimisé pour un coût total de possession optimal.
* Automatisation des déploiements de bout en bout, conformément aux bonnes pratiques AWS, Microsoft et ONTAP.
* Le mode de déploiement _Création rapide_ vous aide à éviter les pièges potentiels liés à la configuration manuelle.




[[automation-with-workload-factory-codebox]]
=== Automatisation avec Workload Factory Codebox

Workload Factory introduit l'automatisation intégrée avec _Codebox_.  Le Codebox offre les avantages d'automatisation suivants :

* *Génération d'extraits de code* : Workload Factory génère des extraits Infrastructure-as-Code (IaC) lors de la création de ressources, permettant une intégration transparente avec les flux de travail d'orchestration existants.
* *Copilote d'infrastructure en tant que code* : Codebox est un copilote d'infrastructure en tant que code (IaC) qui aide les développeurs et DevOps à générer du code pour exécuter n'importe quelle opération prise en charge par Workload Factory.
* *Afficheur de code et catalogue d'automatisation*: La Codebox fournit un afficheur de code pour une analyse rapide de l'automatisation et un catalogue d'automatisation pour une réutilisation rapide future.




[[workload-factory-for-databases-features]]
=== Fonctionnalités de Workload Factory pour les bases de données

Workload Factory for Databases offre les fonctionnalités suivantes :

* *Estimation des coûts* : évaluez les économies potentielles grâce au calculateur d’économies qui estime et détaille les coûts de stockage, de calcul, de licence SQL, de snapshot et de clonage pour les déploiements existants de Microsoft SQL Server et Oracle avec Elastic Block Store, FSx for Windows File Server et sur site, comparés à FSx for ONTAP.
* *Déploiements simples et rapides* : simplifiez et rationalisez le provisionnement des hôtes, des bases de données et des environnements sandbox grâce aux meilleures pratiques intégrées de NetApp, Microsoft et Amazon qui éliminent la complexité de la configuration manuelle pour les instances Microsoft SQL Server et PostgreSQL sur AWS.
+
** Déployez depuis la console Workload Factory en utilisant les modes de création _Rapide_ ou _Avancé_, ou créez, réutilisez et personnalisez des modèles AWS CloudFormation via Codebox pour de futurs déploiements dans plusieurs environnements.
** Créez des bases de données isolées à la demande, avec des configurations de stockage et des clones sandbox pouvant être utilisés pour les tests, l'intégration, les diagnostics et la formation, sans affecter les données de production.


* *Fonctionnalité d'évaluation bien conçue* : analyse en continu vos environnements Microsoft SQL Server et Oracle pour obtenir un rapport complet d'informations, d'opportunités et de recommandations afin de vous aider à atteindre l'excellence opérationnelle, la sécurité, la fiabilité, l'efficacité des performances et l'optimisation des coûts, conformément aux meilleures pratiques AWS.
* *Analyse des erreurs* : analysez et résolvez les erreurs de journal avec l’analyseur IA pour obtenir des messages d’erreur détaillés, des étapes de dépannage et des recommandations pour résoudre les problèmes.
* Gestion centralisée : gérez vos ressources Microsoft SQL Server, Oracle et PostgreSQL sur FSx for ONTAP depuis une interface unique. Dans Workload Factory, visualisez l’infrastructure connectée, les comptes AWS, les informations d’identification, les systèmes de fichiers FSx for ONTAP connectés, l’utilisation du stockage, y compris les volumes NFS et les LUN iSCSI, l’état de la protection, les performances, l’état d’architecture et l’analyse des erreurs.




[[benefits-of-amazon-fsx-for-ontap-for-self-managed-databases]]
== Avantages d'Amazon FSX pour ONTAP pour les bases de données autogérées

* *Durabilité, disponibilité et fiabilité* : FSX for ONTAP offre de nombreuses fonctionnalités qui améliorent la durabilité et la disponibilité des bases de données autogérées hébergées sur FSX for ONTAP, telles que la haute disponibilité prenant en charge les déploiements dans des zones de disponibilité unique et multiple, les snapshots intégrant la cohérence applicative, la reprise après incident améliorée grâce à la réplication et une sauvegarde efficace.
* *Performances et évolutivité* : FSX pour ONTAP offre l'optimisation des performances avec un débit élevé, une faible latence, des connexions réseau haut débit et l'évolutivité avec plusieurs systèmes de fichiers pour faire évoluer les performances d'agrégats requises pour une charge de travail.
* *Gestion et efficacité des données* : FSX pour ONTAP offre de nombreuses fonctionnalités qui améliorent la gestion et l'efficacité des données, telles que les clones fins compacts, le provisionnement fin, la compression et la déduplication, et le Tiering des données rarement utilisées dans le pool de capacité.


link:https://docs.netapp.com/us-en/workload-fsx-ontap/learn-fsx-ontap.html["En savoir plus sur FSx pour ONTAP pour Workload Factory"^] .



[[tools-to-use-netapp-workload-factory]]
== Outils pour utiliser NetApp Workload Factory

Vous pouvez utiliser NetApp Workload Factory avec les outils suivants :

* *Console Workload Factory* : La console Workload Factory fournit une vue visuelle et holistique de vos applications et projets.
* * Console NetApp * : la console NetApp fournit une expérience d'interface hybride afin que vous puissiez utiliser Workload Factory avec d'autres services de données NetApp .
* *Demandez-moi* : utilisez l'assistant IA Ask me pour poser des questions et en savoir plus sur Workload Factory sans quitter la console Workload Factory. Accédez à Demandez-moi depuis le menu d'aide de Workload Factory.
* *CloudShell CLI* : Workload Factory inclut une CLI CloudShell pour gérer et exploiter les environnements AWS et NetApp sur plusieurs comptes à partir d'une seule CLI basée sur un navigateur. Accédez à CloudShell depuis la barre supérieure de la console Workload Factory.
* *API REST* : utilisez les API REST de Workload Factory pour déployer et gérer vos systèmes de fichiers FSx for ONTAP et d'autres ressources AWS.
* *CloudFormation* : utilisez le code AWS CloudFormation pour effectuer les actions que vous avez définies dans la console Workload Factory afin de modéliser, provisionner et gérer les ressources AWS et tierces de la pile CloudFormation dans votre compte AWS.
* *NetApp Terraform provider* : Utilisez Terraform pour créer et gérer les flux de travail d’infrastructure générés dans la console Workload Factory.




[[supported-configurations]]
== Configurations compatibles

Vous pouvez utiliser Workload Factory avec les moteurs de base de données, versions, systèmes d'exploitation et modèles de déploiement suivants, en suivant les bonnes pratiques d'AWS, de NetApp ONTAP, de Microsoft SQL Server, d'Oracle et de PostgreSQL.

[cols="1,1,1,1"]
|===
| Moteur | Version | Système opérateur | Modèle de déploiement 


| Microsoft SQL Server | SQL Server 2016 | Windows Server 2016 | FCI, autonome 


| Microsoft SQL Server | SQL Server 2019 | Windows Server 2016 | FCI, autonome 


| Microsoft SQL Server | SQL Server 2022 | Windows Server 2016 | FCI, autonome 


| Microsoft SQL Server | SQL Server 2016 | Windows Server 2019 | FCI, autonome 


| Microsoft SQL Server | SQL Server 2019 | Windows Server 2019 | FCI, autonome 


| Microsoft SQL Server | SQL Server 2022 | Windows Server 2019 | FCI, autonome 


| Microsoft SQL Server | SQL Server 2016 | Windows Server 2022 | FCI, autonome 


| Microsoft SQL Server | SQL Server 2019 | Windows Server 2022 | FCI, autonome 


| Microsoft SQL Server | SQL Server 2022 | Windows Server 2022 | FCI, autonome 


| Microsoft SQL Server | SQL Server 2025 | Windows Server 2025 | FCI, autonome 


| Microsoft SQL Server | SQL Server 2017 | N'importe lequel | FCI, autonome 


| Microsoft SQL Server | SQL Server 2016, 2017, 2019, 2022 | N'importe lequel | FCI, autonome 


| Microsoft SQL Server | SQL Server 2016, 2017, 2019, 2022 | N'importe lequel | Groupe de disponibilité Always On 


| Oracle | 19c | RHEL, SuSe Linux | Autonome (locataire unique/multi-locataire) 


| Oracle | 21c | RHEL, SuSe Linux | Autonome (locataire unique/multi-locataire) 


| Oracle | 19c | RHEL, SuSe Linux | Autonome (locataire unique/multi-locataire) 


| Oracle | 21c | RHEL, SuSe Linux | Autonome (locataire unique/multi-locataire) 


| Oracle | 19c | RHEL, SuSe Linux | Autonome avec ASM (locataire unique/multi-locataire) 


| Oracle | 21c | RHEL, SuSe Linux | Autonome avec ASM (locataire unique/multi-locataire) 


| Oracle | 19c, 21c | RHEL, SuSe Linux | Data Guard 


| PostgreSQL | PostgreSQL 15 | AMI Amazon Linux 2023 | HA, instance autonome 


| PostgreSQL | PostgreSQL 16 | AMI Amazon Linux 2023 | HA, instance autonome 
|===


[[integrated-aws-services]]
== Services AWS intégrés

Les bases de données incluent les services AWS intégrés suivants :

* CloudFormation
* Simple notification Service
* CloudWatch
* System Manager
* Responsable secrets




[[regions]]
== Régions

Les bases de données sont prises en charge dans toutes les régions commerciales où FSX pour ONTAP est pris en charge. https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["Affichez les régions Amazon prises en charge."^]

Les régions AWS suivantes ne sont pas prises en charge :

* Régions de Chine
* Le cloud secret
* Meilleur cloud secret




[[getting-help]]
== Obtenir de l'aide

Amazon FSX pour NetApp ONTAP est une solution propriétaire AWS. Pour toute question ou tout problème de support technique associé à votre système de fichiers FSX for ONTAP, à votre infrastructure ou à toute solution utilisant ce service, utilisez le centre de support de votre console de gestion AWS pour ouvrir un dossier de support avec AWS. Sélectionnez le service “FSX pour ONTAP” et la catégorie appropriée. Fournissez les informations restantes nécessaires pour créer un dossier de demande de support AWS.

Pour des questions générales sur Workload Factory ou les applications et services Workload Factory, reportez-vous àlink:get-help.html["Obtenez de l'aide pour NetApp Workload Factory pour les bases de données"] .
