---
sidebar: sidebar 
permalink: manage-server.html 
keywords: Microsoft SQL Server instance, server instance, manage host, view host, database host, database instance, manage, unmanage 
summary: 'Gérez les instances Microsoft SQL Server dans l"usine de workloads BlueXP  pour les bases de données.' 
---
= Gérez les instances Microsoft SQL Server dans l'usine de workloads BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Gérez des instances Microsoft SQL Server pour surveiller l'état des instances et des bases de données, l'utilisation des ressources, la protection et les performances du stockage dans l'usine de workloads BlueXP  pour les bases de données.

Les bases de données peuvent uniquement gérer les instances de Microsoft SQL Server avec le stockage du système de fichiers FSX for ONTAP.



== Gestion des instances Microsoft SQL Server

La gestion des instances de Microsoft SQL Server comprend les tâches suivantes :

* Gérer une instance hôte
* Afficher une instance gérée
* Afficher les bases de données
* Annuler la gestion d'une instance hôte


Pour effectuer l'une de ces tâches, vous devez link:detect-host.html["détecter une ou plusieurs instances hôtes"^].



== Gérer une instance hôte

Gérer les instances Microsoft SQL Server détectées ou non gérées pour un hôte.

Pour gérer une instance hôte dans un réseau privé sans connectivité externe, les terminaux suivants doivent être disponibles dans le VPC en association avec les sous-réseaux où sont présents les serveurs SQL. Assurez-vous que les points de terminaison de l'interface autorisent le port 443 dans le groupe de sécurité connecté.

* `S3 Gateway/endpoint`
* `ssm`
* `ssmmessages`
* `fsx`


.Avant de commencer
Avant de commencer, remplissez les conditions préalables suivantes :

* Vous devez avoir une instance détectée dans l'hôte qui est disponible pour la gestion.
* PowerShell7 est nécessaire pour gérer l'instance de base de données. Installez PowerShell7 manuellement en vous reportant link:https://learn.microsoft.com/en-us/powershell/scripting/developer/module/installing-a-powershell-module?view=powershell-7.4["Documentation Microsoft PowerShell pour Windows"^]à la .
* Toutes les opérations de gestion sont exécutées par l'agent AWS System Manager avec les `NT Authority\SYSTEM` privilèges utilisateur. Fournissez les autorisations suivantes à l' `NT Authority\SYSTEM` utilisateur sur le serveur de base de données :
+
** `“ALTER SETTINGS”`
** `“CONTROL SERVER”`
** `“ALTER ANY DATABASE”`
** `“VIEW ANY DEFINITION”`
** `“CONNECT ANY DATABASE”`
** `“CREATE ANY DATABASE”`




.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans la mosaïque bases de données, sélectionnez *aller à bases de données Inventaire*.
. Dans bases de données, sélectionnez l'onglet *Inventaire*.
. Cliquez sur *gérer* dans la ligne de l'hôte à gérer.
. Sélectionnez une ou plusieurs instances hôtes à gérer.
. Cliquez sur *gérer*.


L'opération échoue lorsque Microsoft SQL Server manque certains modules PowerShell et scripts de gestion. Workload Factory déclenche un travail de ressource de préparation pour installer les modules et les scripts manquants que vous pouvez afficher dans l'onglet surveillance des travaux. Une fois la tâche terminée, réessayez de gérer l'instance hôte.



== Afficher une instance gérée

Vous pouvez afficher une instance gérée en suivant ces étapes.

.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans la mosaïque bases de données, sélectionnez *aller à bases de données Inventaire*.
. Dans bases de données, sélectionnez l'onglet *Inventaire*.
. Cliquez sur la flèche déroulante pour développer la ligne de l'hôte et afficher ses instances gérées.
+
L'hôte se développe et les instances hôtes s'affichent.

. Cliquez sur le menu à trois points de l'instance à afficher, puis sélectionnez *Afficher l'instance*.


.Résultat
La vue d'ensemble de l'instance s'affiche dans l'onglet Inventaire.



== Afficher les bases de données

Vous pouvez afficher les bases de données gérées par l'instance gérée en suivant ces étapes.

.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans la mosaïque bases de données, sélectionnez *aller à bases de données Inventaire*.
. Dans bases de données, sélectionnez l'onglet *Inventaire*.
. Cliquez sur la flèche déroulante pour développer la ligne de l'hôte et afficher ses bases de données.
+
L'hôte se développe et les instances hôtes s'affichent.

. Cliquez sur le menu à trois points de l'instance contenant les bases de données à afficher.
. Sélectionnez *Afficher les bases de données*.


.Résultat
La liste des bases de données de l'instance s'affiche dans l'onglet Inventaire.



== Annuler la gestion d'une instance hôte

Annulez la gestion d'une instance hôte en suivant ces étapes.

.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans la mosaïque bases de données, sélectionnez *aller à bases de données Inventaire*.
. Dans bases de données, sélectionnez l'onglet *Inventaire*.
. Cliquez sur la flèche déroulante pour développer la ligne de l'instance hôte à gérer.
+
L'hôte se développe et les instances hôtes s'affichent.

. Cliquez sur le menu des trois points de l'instance à gérer.
. Sélectionnez *Unmanage*.


.Résultat
L'instance hôte n'est plus gérée.
