---
sidebar: sidebar 
permalink: monitor-databases.html 
keywords: monitor databases, monitor jobs, track database jobs 
summary: 'Suivez les tâches de base de données et surveillez les bases de données au sein de l"usine de workloads BlueXP .' 
---
= Surveillez les bases de données en usine de workloads BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Suivez les tâches de base de données et surveillez les bases de données au sein de l'usine de workloads BlueXP .

.Description de la tâche
Les bases de données permettent de surveiller la progression des tâches et de diagnostiquer et dépanner en cas de défaillance. Vous pouvez filtrer les travaux par type et par état, rechercher des travaux à l'aide de la fonction de recherche et télécharger la table des travaux.

La surveillance des tâches prend en charge jusqu'à trois niveaux de surveillance selon le travail. Par exemple, pour la création de nouvelles bases de données et de clones sandbox, la surveillance des tâches suit les travaux et sous-travaux parents.

Niveaux de surveillance des tâches::
+
--
* Niveau 1 (travail parent) : assure le suivi du travail de déploiement de l'hôte.
* Niveau 2 (sous-travail) : assure le suivi des sous-travaux liés au travail parent de déploiement hôte.
* Niveau 3 (tâche) : liste la séquence des actions entreprises sur chaque ressource.


--
État des tâches:: La fonction de surveillance des tâches effectue le suivi des tâches _en cours_, _terminées_, _terminées avec des problèmes_, et _échouées_, quotidiennes, hebdomadaires, bimensuelles et mensuelles.
Conservation des événements de travail:: Les événements de surveillance des travaux sont conservés dans l'interface utilisateur pendant 30 jours.




== Surveiller les tâches

.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans la mosaïque bases de données, sélectionnez *aller à l'inventaire des bases de données*.
. Dans bases de données, sélectionnez l'onglet *surveillance des travaux*.
. Dans l'onglet surveillance des travaux, utilisez les filtres ou la recherche pour affiner les résultats des travaux. Vous pouvez également télécharger un rapport de travaux.
. Cliquez sur le menu à trois points du travail et cliquez sur *aller à CloudFormation* pour afficher le journal du travail dans la console AWS CloudFormation.

