---
sidebar: sidebar 
permalink: optimize-overview.html 
keywords: database configuration issues, issues, analyze, scan, optimize, improve, database configuration, Amazon FSx for NetApp ONTAP, FSx for ONTAP, recommendation, recommendations, storage, compute, application, resiliency, scan, optimization, SQL Server, host, instance 
summary: 'Workload Factory for Databases analyse régulièrement les configurations Microsoft SQL Server et Oracle pour déterminer s"il existe des problèmes.' 
---
= Analyse de configuration pour les environnements de base de données dans Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Workload Factory for Databases analyse régulièrement les configurations de base de données pour déterminer s'il existe des problèmes avec les déploiements Microsoft SQL Server et Oracle sur le stockage Amazon FSx for NetApp ONTAP .  Lorsque des problèmes sont détectés, Workload Factory vous montre quels sont les problèmes et explique ce qui doit être modifié pour garantir que vos configurations de base de données atteignent des performances optimales, une rentabilité optimale et la conformité aux meilleures pratiques.

Les fonctionnalités principales comprennent :

* Analyse quotidienne de la configuration
* Validations automatiques des meilleures pratiques
* Recommandations de dimensionnement approprié
* Observabilité proactive
* Des analyses à l'action
* Framework Advisor bien conçu d'AWS




== Composantes de l'analyse de configuration

L'analyse de configuration comprend les composants suivants :

État bien conçu:: L'état « bien architecturé » fait référence à l'état général de vos configurations de base de données ; les configurations sont catégorisées comme « optimisées », « non optimisées » ou « surdimensionnées ». L'état d'architecture correcte d'une configuration est référencé depuis une instance Microsoft SQL Server ou une base de données Oracle dans la console Workload Factory.
Score bien conçu:: Le score inclut toutes les configurations actuellement analysées et s'affiche sous forme de pourcentage. Un score de 25 % signifie que 25 % de vos déploiements de bases de données sont bien architecturés. Le score d'architecture bien conçue est référencé depuis l'écran *Architecture bien conçue* et depuis une instance Microsoft SQL Server ou une base de données Oracle dans la console Workload Factory.
Catégories de configuration:: Les configurations sont organisées dans les catégories suivantes : stockage, calcul, application, résilience et clonage. Chaque catégorie comprend des évaluations de configuration spécifiques qui sont analysées régulièrement. Les catégories de configuration sont référencées à partir de l'écran *Bien architecturé* et à partir d'une instance Microsoft SQL Server ou d'une base de données Oracle dans la console Workload Factory.




== Portée de l'analyse

La portée de l'optimisation varie en fonction du composant évalué. Par exemple, l'optimisation du stockage a lieu au niveau de l'instance SQL alors que l'optimisation du calcul a lieu au niveau de l'hôte.



== Exigences d'analyse

Pour une analyse complète de l'environnement de base de données, les ressources doivent être enregistrées et en ligne.

link:register-instance.html["Apprenez à enregistrer des ressources."]

.Et la suite
link:optimize-configurations.html["Mettre en œuvre des configurations de base de données bien architecturées"]
