---
sidebar: sidebar 
permalink: optimize-configurations.html 
keywords: optimize, configuration, storage, compute, application, resiliency assessment, scan, optimization, Microsoft SQL Server, host, instance, FSx for ONTAP 
summary: 'Workload Factory for Databases analyse les configurations Microsoft SQL Server en fournissant des informations et des recommandations pour vous aider à atteindre l"excellence opérationnelle.' 
---
= Implémenter des configurations de base de données bien architecturées dans Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Grâce aux analyses de configuration et aux recommandations, exploitez Workload Factory pour mettre en œuvre les meilleures pratiques pour vos configurations de base de données. Vous pouvez facilement identifier les problèmes et prendre des mesures pour améliorer l'architecture des configurations qui ne sont pas optimisées en termes de fiabilité, de sécurité, d'efficacité, de performances et de coût.

.Description de la tâche
Workload Factory analyse quotidiennement les configurations de bases de données. Cette analyse fournit des informations et des recommandations, ainsi que des options pour corriger automatiquement les problèmes de configuration afin que vos configurations soient conformes aux meilleures pratiques.

Vous disposez d'options pour examiner les recommandations relatives aux problèmes de configuration et résoudre ces problèmes à partir de l'inventaire des bases de données dans la console de l'usine de charge de travail.

Ce qui est analysé:: Workload Factory analyse l'état bien architecturé des configurations suivantes pour les instances Microsoft SQL Server :
+
--
* Dimensionnement du stockage : inclut le niveau de stockage, la marge du système de fichiers, la taille du disque du journal et la taille du disque TempDB
* Disposition du stockage : inclut le placement des fichiers de données utilisateur, le placement des fichiers journaux et le placement de TempDB
* Configuration du stockage : inclut la gestion de la capacité, le provisionnement léger, la politique de hiérarchisation, les instantanés, l'état Microsoft Multipath I/O (MPIO) et le paramètre de délai d'expiration MPIO
* Calcul : inclut le dimensionnement approprié, les correctifs du système d'exploitation et les paramètres de la carte réseau tels que le RSS (Receive Side Scaling) et le déchargement TCP
* Applications : inclut les licences Microsoft SQL Server, le correctif Microsoft SQL Server et les paramètres MAXDOP
* Résilience : inclut les snapshots locaux, les sauvegardes FSX pour ONTAP et la réplication interrégionale (CRR)
* Clones : inclut des options pour actualiser et supprimer les clones (bacs à sable) qui ont été créés dans ou en dehors de l'usine de charge de travail et qui datent de plus de 60 jours


--


.Avant de commencer
* Vous devez avoir link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Informations d'identification du compte AWS et autorisations de lecture/écriture"^] pour analyser vos configurations de base de données.
* Pour évaluer le stockage d’une instance Microsoft SQL Server, l’instance doit être enregistrée dans la fabrique de charges de travail et le type de stockage doit être FSx pour ONTAP. link:register-instance.html["Découvrez comment enregistrer une instance d’hôte."]
* Vérifiez attentivement chaque recommandation avant de choisir de corriger un paramètre ou une configuration. Pour les paramètres RSS et MAXDOP, nous vous suggérons de tester les paramètres recommandés pour déterminer les améliorations de performances avant d'apporter des modifications à votre environnement de production.



NOTE: Le processus de correction peut entraîner des temps d'indisponibilité d'instance ou des interruptions de service. Assurez-vous de lire attentivement la recommandation avant de choisir de corriger une configuration.

.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans la mosaïque bases de données, sélectionnez *aller à l'inventaire des bases de données*.
. Dans l'onglet *Inventaire*, sélectionnez l'onglet *instances*.
. Sélectionnez *Résoudre les problèmes* pour afficher les problèmes de configuration de l'instance.
. Sur la page d’état Bien architecturé de l’instance hôte, examinez les résultats de l’analyse.
+
Vous pouvez filtrer les problèmes de configuration par catégories, sous-catégories, statut, gravité et balises.

+
Vous pouvez également télécharger un rapport des résultats en sélectionnant *Exporter PDF*.

. Sélectionnez la flèche déroulante pour afficher les recommandations pour une configuration. Les recommandations incluent les meilleures pratiques, les pièges potentiels des configurations non optimisées et des considérations importantes. Assurez-vous de revoir attentivement la recommandation.
. Sélectionnez pour *Afficher et corriger* les problèmes de configuration lorsque l'option est disponible.
+
*Sélectionner tout* est la valeur par défaut, mais vous pouvez sélectionner des ressources spécifiques à corriger.

+
.. Pour toutes les configurations, à l’exception du nettoyage des clones, consultez les détails de la recommandation pour savoir ce qui se passera si vous choisissez de résoudre le problème. Certaines opérations de correction peuvent entraîner des interruptions de service ou des temps d'arrêt des instances.
.. Pour le nettoyage des clones, sélectionnez les bases de données clonées (sandbox) à actualiser ou à supprimer.
+
*** L'actualisation d'un clone le synchronise avec sa base de données source. L'actualisation est uniquement disponible pour les clones créés en usine de la charge de travail.
*** La suppression d'un clone le supprime définitivement, libère de l'espace de stockage et réduit les coûts. Vous pouvez supprimer les clones créés dans et en dehors de l'usine de la charge de travail.




. Sélectionnez *Continuer* pour résoudre le problème de configuration.


.Résultat
Workload Factory commence à résoudre le(s) problème(s). Sélectionnez l'onglet *surveillance des travaux* pour afficher l'état de l'opération.
