---
sidebar: sidebar 
permalink: optimize-overview.html 
keywords: continuous optimization, optimize, assess, assessment, scan, optimization, Microsoft SQL Server, Amazon FSx for NetApp ONTAP, FSx for ONTAP, recommendation, recommendations 
summary: 'L"usine de workloads BlueXP  pour les bases de données assure une optimisation continue des déploiements Microsoft SQL Server sur Amazon FSX pour le stockage NetApp ONTAP.' 
---
= Optimisation continue de l'usine de workloads BlueXP  pour les bases de données
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
L'usine de workloads BlueXP  pour les bases de données assure une optimisation continue des déploiements Microsoft SQL Server sur Amazon FSX pour le stockage NetApp ONTAP.

L'optimisation continue analyse et évalue automatiquement votre infrastructure de base de données à grande échelle pour s'assurer que les environnements de grande envergure atteignent des niveaux de performance optimaux, une meilleure rentabilité et une conformité aux bonnes pratiques. Cette fonctionnalité fournit un rapport complet d'informations et de recommandations d'optimisation.

L'optimisation continue vous permet de détecter les problèmes de votre infrastructure de base de données, d'identifier les changements à apporter et de prendre des mesures.

Les fonctionnalités principales comprennent :

* Évaluation continue
* Validations automatiques des meilleures pratiques
* Recommandations de dimensionnement approprié
* Observabilité proactive
* Des analyses à l'action
* Framework Advisor bien conçu d'AWS


La portée de l'optimisation varie en fonction du composant évalué. Par exemple, l'optimisation du stockage a lieu au niveau de l'instance SQL alors que l'optimisation du calcul a lieu au niveau de l'hôte.

link:optimize-configurations.html["Optimisez les configurations pour les déploiements Microsoft SQL Server"]
