---
sidebar: sidebar 
permalink: postpone-analysis.html 
keywords: postpone configuration analysis, dismiss configuration analysis, postpone, dismiss, stop, optimization, Microsoft SQL Server, host, instance, FSx for ONTAP 
summary: 'Différez ou ignorez l"analyse de configurations de base de données spécifiques qui ne s"appliquent pas à votre environnement de base de données afin d"éviter les alertes inutiles et les résultats d"optimisation imprécis.' 
---
= Reporter ou ignorer l'analyse des configurations de base de données
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Différez ou ignorez l'analyse de configurations de base de données spécifiques qui ne s'appliquent pas à votre environnement de base de données afin d'éviter les alertes inutiles et les résultats d'optimisation imprécis. Vous pouvez à tout moment réactiver une analyse de configuration différée ou rejetée.

.Description de la tâche
Les exigences des applications pour les configurations de base de données varient. Workload Factory vous offre deux options pour ignorer l'analyse de configurations de base de données spécifiques afin que vous puissiez surveiller uniquement les problèmes pertinents et obtenir une vue précise de l'état de santé des configurations pertinentes. Lorsqu'une analyse de configuration spécifique est reportée ou rejetée, la configuration n'est pas incluse dans le score d'optimisation total.

Vous pouvez reporter, ignorer et réactiver l'analyse de configuration au niveau de la configuration et au niveau de l'instance SQL Server.

* *Différer de 30 jours* : retarder l'analyse arrêtera l'analyse pendant 30 jours. Au bout de 30 jours, l'analyse redémarre automatiquement.
* *Rejeter*: Le rejet de l'analyse retarde indéfiniment l'analyse. Vous pouvez redémarrer l'analyse si nécessaire.


Vous pouvez reporter ou ignorer les configurations suivantes pour les instances de Microsoft SQL Server :

* Dimensionnement du stockage : inclut le niveau de stockage, la marge du système de fichiers, la taille du disque du journal et la taille du disque TempDB
* Disposition du stockage : inclut le placement des fichiers de données utilisateur, le placement des fichiers journaux et le placement de TempDB
* Configuration du stockage : inclut la gestion de la capacité, le provisionnement fin, la règle de hiérarchisation, les snapshots, l'état des E/S à chemins d'accès multiples, la règle et les sessions, etc
* Calcul : inclut le dimensionnement approprié, les correctifs du système d'exploitation et les paramètres de la carte réseau tels que le RSS (Receive Side Scaling) et le déchargement TCP
* Applications : inclut les licences Microsoft SQL Server, le correctif Microsoft SQL Server et les paramètres MAXDOP
* Résilience : inclut les snapshots locaux, les sauvegardes FSX pour ONTAP et la réplication interrégionale (CRR)
* Clones


Les instructions suivantes décrivent comment reporter, rejeter ou réactiver une analyse au niveau de la configuration. Pour effectuer les tâches suivantes pour des instances SQL Server spécifiques, démarrez dans l'onglet *Dashboard*.

[role="tabbed-block"]
====
.Reporter
Délai de 30 jours avant l'arrêt d'une analyse de configuration. Au bout de 30 jours, l'analyse redémarre automatiquement.

--
.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans la mosaïque bases de données, sélectionnez *aller à l'inventaire des bases de données*.
. Dans l'onglet *Inventaire*, faites défiler jusqu'à la configuration à reporter, sélectionnez le menu à trois points, puis sélectionnez *différer pendant 30 jours*.
. Sélectionnez *Continuer*.


.Résultat
L'analyse de la configuration s'arrête pendant 30 jours.

--
.Rejeter
Ignorer pour arrêter indéfiniment une analyse de configuration. Vous pouvez redémarrer l'analyse si nécessaire.

--
.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans la mosaïque bases de données, sélectionnez *aller à l'inventaire des bases de données*.
. Dans l'onglet *Inventaire*, faites défiler jusqu'à la configuration à ignorer, sélectionnez le menu à trois points, puis sélectionnez *rejeter*.
. Sélectionnez *Continuer*.


.Résultat
L'analyse de la configuration s'arrête.

--
.Réactiver
Réactiver à tout moment une analyse de configuration différée ou rejetée.

--
.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans la mosaïque bases de données, sélectionnez *aller à l'inventaire des bases de données*.
. Dans l'onglet *Inventaire*, faites défiler jusqu'à la configuration à réactiver, sélectionnez le menu à trois points, puis sélectionnez *réactiver*.
. Sélectionnez *Continuer*.


.Résultat
L'analyse de la configuration est réactivée et se produit quotidiennement à l'avenir.

--
====