---
sidebar: sidebar 
permalink: split-clone.html 
keywords: split, clone, source, new database 
summary: Divisez un clone de base de données à partir de la base de données source pour créer une nouvelle base de données dans NetApp Workload Factory for Databases. 
---
= Diviser un clone de base de données à partir de la base de données source
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Dans NetApp Workload Factory for Databases, la division d'un clone de base de données à partir de sa base de données source crée une nouvelle base de données qui consommera une certaine quantité de capacité de stockage.  Le clone est supprimé lorsque la division est terminée et la nouvelle base de données apparaît dans l'inventaire.

.Avant de commencer
Évaluez la capacité de stockage nécessaire pour la nouvelle base de données. Si nécessaire, link:https://docs.netapp.com/us-en/workload-fsx-ontap/increase-file-system-capacity.html["augmenter la capacité du système de fichiers"^] pour le système de fichiers FSX pour ONTAP avant de commencer.

.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans la mosaïque bases de données, sélectionnez *aller à l'inventaire des bases de données*.
. Dans le menu Bases de données, sélectionnez *Bacs à sable*.
. Dans Sandboxes, sélectionnez le menu d’action du clone de base de données que vous souhaitez diviser.
. Sélectionnez *Fractionner*.
. Dans la boîte de dialogue Fractionner, sélectionnez *Fractionner*.

