---
sidebar: sidebar 
permalink: view-databases.html 
keywords:  
summary: 'Pour obtenir un résumé des ressources de base de données dans Workload Factory, consultez toutes les bases de données de l"inventaire. Vous pouvez également consulter les bases de données par instance enregistrée.' 
---
= Afficher les bases de données dans Workload Factory pour les bases de données
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Pour obtenir un résumé des ressources de base de données dans Workload Factory, consultez toutes les bases de données de l'inventaire. Vous pouvez également consulter les bases de données par instance enregistrée.

.Avant de commencer
* Les instances contenant des ressources de base de données doivent disposer de FSx pour le stockage du système de fichiers ONTAP.
* Vous devez enregistrer des instances dans Workload Factory pour afficher les bases de données. Découvrez comment link:register-instance.html["enregistrer une instance"] .


.Étapes
[role="tabbed-block"]
====
.Afficher les bases de données pour une seule instance
--
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans la mosaïque bases de données, sélectionnez *aller à l'inventaire des bases de données*.
. Dans bases de données, sélectionnez l'onglet *Inventaire*.
. Cliquez sur le menu à trois points de l'instance, puis sélectionnez *Afficher les bases de données*.


Les bases de données s'affichent pour l'instance unique dans l'onglet Bases de données.

--
.Afficher les bases de données pour toutes les instances
--
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans la mosaïque bases de données, sélectionnez *aller à l'inventaire des bases de données*.
. Dans bases de données, sélectionnez l'onglet *Inventaire*.
. Sélectionnez l'onglet *Bases de données*.
+
Les bases de données s'affichent pour toutes les instances enregistrées.



--
====